#!/usr/bin/env python3
"""
Maintain docs/branch/BRANCH_TIMELINE.md and scaffold branch summaries.

Invoked by repo-local git hooks (see .githooks/) and manually:
  python3 scripts/branch_docs.py regenerate-timeline
  python3 scripts/branch_docs.py ensure-summary <branch-name>
"""
from __future__ import annotations

import argparse
import datetime as _dt
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_BRANCH = REPO_ROOT / "docs" / "branch"
TEMPLATE = DOCS_BRANCH / "BRANCH_SUMMARY_TEMPLATE.md"
TIMELINE = DOCS_BRANCH / "BRANCH_TIMELINE.md"

META_RE = re.compile(
    r"^\s*-\s*\*\*(Branch|Status|Opened on|Closed on|Merged into|Merge strategy|Last updated)\*\*:\s*(.*)$"
)
ACCOMPLISH_RE = re.compile(r"^\s*-\s+(.*)$")


def _today() -> str:
    return _dt.date.today().isoformat()


def summary_filename(branch: str) -> str:
    safe = branch.replace("/", "_").replace("\\", "_")
    return f"BRANCH_SUMMARY_{safe}.md"


def parse_summary(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    meta: dict[str, str] = {}
    accomplishments: list[str] = []
    in_acc = False
    for line in text.splitlines():
        m = META_RE.match(line)
        if m:
            key, val = m.group(1), m.group(2).strip()
            meta[key] = val
            in_acc = False
            continue
        if line.strip() == "## Accomplishments":
            in_acc = True
            continue
        if in_acc:
            if line.startswith("## "):
                break
            am = ACCOMPLISH_RE.match(line)
            if am and not line.strip().startswith("- Replace these"):
                accomplishments.append(am.group(1).strip())
            elif line.strip() == "" and accomplishments:
                pass
    branch = meta.get("Branch", "")
    if not branch:
        return None
    last = meta.get("Last updated", "")
    return {
        "path": path,
        "branch": branch,
        "meta": meta,
        "accomplishments": accomplishments[:3],
        "last_updated": last,
    }


def regenerate_timeline() -> None:
    summaries = sorted(DOCS_BRANCH.glob("BRANCH_SUMMARY_*.md"))
    rows: list[dict] = []
    for p in summaries:
        if p.name == "BRANCH_SUMMARY_TEMPLATE.md":
            continue
        parsed = parse_summary(p)
        if parsed:
            rows.append(parsed)

    def sort_key(r: dict) -> tuple:
        lu = r["last_updated"]
        if not lu or lu == "-":
            return ("9999", r["branch"])
        return (lu, r["branch"])

    rows.sort(key=sort_key, reverse=True)

    lines = [
        "<!-- Generated by scripts/branch_docs.py — do not edit by hand -->",
        "",
        "# Branch timeline",
        "",
        "This file is regenerated by `scripts/branch_docs.py` (via git hooks). It lists branch summaries in **reverse chronological order by Last updated** (newest first).",
        "",
    ]

    for r in rows:
        branch = r["branch"]
        meta = r["meta"]
        acc = r["accomplishments"]
        link_name = r["path"].name
        lines.append(f"### {branch}")
        lines.append("")
        lines.append("**Accomplishments**")
        lines.append("")
        if acc:
            for a in acc[:3]:
                lines.append(f"- {a}")
        else:
            lines.append("- _(see summary)_")
        lines.append("")
        opened = meta.get("Opened on", "")
        closed = meta.get("Closed on", "")
        merged_into = meta.get("Merged into", "")
        strategy = meta.get("Merge strategy", "")
        status = meta.get("Status", "open")
        if status == "closed" and closed and closed != "-":
            closed_cell = closed
        else:
            closed_cell = "open"
        last_u = meta.get("Last updated", "")
        lines.append(
            "| Opened | Last Updated | Closed | Merged Into | Merged Strategy | Summary |"
        )
        lines.append("| --- | --- | --- | --- | --- | --- |")
        lines.append(
            f"| {opened} | {last_u} | {closed_cell} | {merged_into} | {strategy} | [summary]({link_name}) |"
        )
        lines.append("")
        lines.append("")
        lines.append("---")
        lines.append("")

    TIMELINE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def ensure_summary(branch: str) -> None:
    if branch in ("main", "master", "trunk"):
        return
    out = DOCS_BRANCH / summary_filename(branch)
    if out.exists():
        return
    if not TEMPLATE.exists():
        sys.stderr.write(f"Missing template: {TEMPLATE}\n")
        sys.exit(1)
    today = _today()
    tpl = TEMPLATE.read_text(encoding="utf-8")
    tpl = tpl.replace("{{BRANCH}}", branch)
    tpl = tpl.replace("{{TODAY}}", today)
    out.write_text(tpl, encoding="utf-8")
    print(f"Created {out}")


def validate_summary(path: Path) -> list[str]:
    errors: list[str] = []
    text = path.read_text(encoding="utf-8")
    required_sections = [
        "## Metadata",
        "## Accomplishments",
        "## Planned work",
        "## Executed work",
        "## Back-and-forth / iteration notes",
        "## Problems + resolutions",
        "## Validation",
        "## Final changelog-style outcome",
    ]
    for sec in required_sections:
        if sec not in text:
            errors.append(f"Missing section: {sec}")
    required_meta = [
        "Branch",
        "Status",
        "Opened on",
        "Closed on",
        "Merged into",
        "Merge strategy",
        "Last updated",
    ]
    for key in required_meta:
        if f"**{key}**:" not in text:
            errors.append(f"Missing metadata: {key}")
    return errors


def touch_last_updated(path: Path, today: str) -> None:
    lines = path.read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    for line in lines:
        if re.match(r"^\s*-\s*\*\*Last updated\*\*:", line):
            out.append(f"- **Last updated**: {today}")
        else:
            out.append(line)
    path.write_text("\n".join(out) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Branch docs helper for wav2hyp")
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("regenerate-timeline", help="Rewrite BRANCH_TIMELINE.md")

    p_ensure = sub.add_parser("ensure-summary", help="Create summary from template if missing")
    p_ensure.add_argument("branch", help="Git branch name")

    p_val = sub.add_parser("validate-summary", help="Validate summary file")
    p_val.add_argument("path", type=Path, help="Path to BRANCH_SUMMARY_*.md")

    p_touch = sub.add_parser("touch-last-updated", help="Set Last updated to today")
    p_touch.add_argument("path", type=Path)

    args = ap.parse_args()

    if args.cmd == "regenerate-timeline":
        regenerate_timeline()
    elif args.cmd == "ensure-summary":
        ensure_summary(args.branch)
    elif args.cmd == "validate-summary":
        errs = validate_summary(args.path)
        if errs:
            for e in errs:
                print(e, file=sys.stderr)
            sys.exit(1)
    elif args.cmd == "touch-last-updated":
        touch_last_updated(args.path, _today())


if __name__ == "__main__":
    main()
